"""Añadir campo orden a Video

Revision ID: 034ddefc4356
Revises: 
Create Date: 2024-09-20 19:05:48.994551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034ddefc4356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
