"""Eliminar el campo orden de Video

Revision ID: f6d5643a491b
Revises: 034ddefc4356
Create Date: 2024-09-21 17:12:00.310822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d5643a491b'
down_revision = '034ddefc4356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
